### ISSUE TITLE
建议获取南开和清华的同学的说法。

### ISSUE THREAD

**Issue by ytxing** [jsk-record/jsk-record#1]
如题。我就不信这种事情还能被学生默许了？还是因为他在科大有关系所以硬气了。这个要找外校同学询问一下。

**Comment by jsk-record** [comment]
你好，感谢关注！
这个我不太了解，但是我在 `README.md` 里加了“其他”部分，请知情的同学来贡献信息。
![image](https://user-images.githubusercontent.com/62491678/77242400-e722b000-6c38-11ea-9289-aeca20a5dbb1.png)

**Comment by yylidiw** [comment]
话说这个课程是指软件工程这课吗？这课应该所有院校都开？
所以是特指和计蒜客结合的？可我们贵系的课都是自己的老师讲的呀。。。所以这个开过是怎么定义的呢？

**Comment by jsk-record** [comment]
> 话说这个课程是指软件工程这课吗？这课应该所有院校都开？
> 所以是特指和计蒜客结合的？可我们贵系的课都是自己的老师讲的呀。。。所以这个开过是怎么定义的呢？

抱歉，表述不准确，已经更新，请查看现在的 `README.md`。

[计蒜客 & 南开大学软件学院 | 2018 暑期软件工程实践](https://www.sohu.com/a/253282206_286966)

我暂未找到和清华大学合作的相关报道，故暂认为没有和清华大学合作。有知情同学请提 PR 补充。
